spring:
  config:
    import: optional:classpath:application-template.yml

  datasource:
    url: jdbc:mariadb://localhost:3306/ai-dea
    username: root
    password: mariadb
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true

server:
  port: 9009

logging:
  level:
    com.spring.aidea: DEBUG
    org.hibernate.SQL: DEBUG
    # ????? ?? ????? ?? ??
    org.springframework.web: DEBUG
    # SQL ???? ??? ??
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# jwt setting
jwt:
  # secret key (실제 운영에서는 환경변수로 관리)
  secret: oIirSuZv9VNydoYp4h2ARrqwxRyPVZW82XGB2MovuKs=
  # 만료시간 (ms) - 24 hour
  expiration: 86400000

# Gemini API Key는 application-template.yml 또는 환경변수에서 로드
gemini:
  api:
    key: ${GEMINI_API_KEY:}
