spring:
  config:
    import:

  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true

server:
  port:

logging:
  level:
    com.spring.aidea: DEBUG
    org.hibernate.SQL: DEBUG
    # ????? ?? ????? ?? ??
    org.springframework.web: DEBUG
    # SQL ???? ??? ??
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# jwt setting
jwt:
  # secret key (실제 운영에서는 환경변수로 관리)
  secret:
  # 만료시간 (ms) - 24 hour
  expiration:

# Gemini API Key는 application-template.yml 또는 환경변수에서 로드
gemini:
  api:
    # API 호출을 위한 URL. RestTemplate이 {apiKey} 부분을 실제 키로 치환합니다.
    url: ""
    # API 키는 application-template.yml 또는 환경 변수에서 가져옵니다.
    key: ${GEMINI_API_KEY:}
